hhru/nuts-and-bolts

nuts-and-bolts/src/main/java/ru/hh/nab/JerseyGutsModule.java
nuts-and-bolts/src/main/java/ru/hh/nab/grizzly/BlockedQueueLimitedThreadPool.java
nuts-and-bolts/src/main/java/ru/hh/nab/grizzly/SimpleGrizzlyWebServer.java

https://jira.hh.ru/browse/HH-46105
Добавил опцию selector.blockOnQueueOverflow
Если selector.blockOnQueueOverflow==true, то селекторы засыпают и не принимают соединения. Эффективно использовать с системной настройкой sysctl -w net.ipv4.tcp_abort_on_overflow=1.
Попутно вынес настройки сервера в SimpleGrizzlyWebServer.

HH-46105 add selector.blockOnQueueOverflow option

---

nuts-and-bolts/src/main/java/ru/hh/nab/jetty/JettyServerFactory.java

Для проекта хамелеон, использующего наб, необходим механизм сессий. Для использования HttpSession необходим SessionManager, однако создавать его лучше всего в фабрике джетти-сервера. В этом пул-реквесте добавлена возможность создавать менеджера при определенной настройке в файле settings, в случае ее отсутствия все остается как прежде.

[adding-session-manager] added the ability to create a SessionManager

---

nab-hibernate/src/main/java/ru/hh/nab/hibernate/transaction/ExecuteOnDataSource.java
nab-hibernate/src/main/java/ru/hh/nab/hibernate/transaction/ExecuteOnDataSourceAspect.java
nab-hibernate/src/main/java/ru/hh/nab/hibernate/transaction/ExecuteOnDataSourceTransactionCallback.java
nab-hibernate/src/main/java/ru/hh/nab/hibernate/transaction/ExecuteOnDataSourceWrappedException.java
nab-tests/src/test/java/ru/hh/nab/datasource/ExecuteOnDataSourceAspectTest.java

https://jira.hh.ru/browse/HH-100964
Выкидываем изначальное (а не обёрнутое) исключение из метода, помеченного `@ExecuteOnDataSource`.

HH-100964 throw original exception from ExecuteOnDataSourceAspect

---

nab-logging/pom.xml
nab-starter/pom.xml
pom.xml

В рамках https://jira.hh.ru/browse/PORTFOLIO-7487 хотим поднять спринг до 5.2.2 и jackson до 2.10.0, чтоб спринг-кафку 2.3.4 использовать.
В хх.ру тесты прогнал с новым набом/спрингом/jackon https://github.com/hhru/hh.ru/pull/6730

HH-101449 up spring to 5.2.2.RELEASE, up jackson to 2.10.0

---

nab-jclient/pom.xml
nab-kafka/pom.xml
nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/Ack.java
nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/DefaultListenerFactory.java
nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/DeserializerSupplier.java
nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/ListenStrategy.java
nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/Listener.java
nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/ListenerFactory.java
nab-kafka/src/main/java/ru/hh/nab/kafka/serialization/JacksonDeserializerSupplier.java
nab-kafka/src/main/java/ru/hh/nab/kafka/util/ConfigProvider.java
nab-kafka/src/test/java/ru/hh/nab/kafka/util/ConfigProviderTest.java
pom.xml

https://jira.hh.ru/browse/HH-101486
Начал работу над консюмером.
Решил остановится на нескольких основных интерфейсах:
1. ListenerFactory с методом listenTopic
2. Принимает в кач-ве аргумента ListenStrategy с методом `onMessagesBatch(List<T>, Ack)` 
3. Возвращает Listener, чтобы была возможность остановить контейнер (как в энричере)
Написал дефолтную реализацию ListenerFactory и попробовал ее в spam-detector https://github.com/hhru/spam-detector/pull/19/commits/e69e589e7d3ef2afa9f7f71ead7c2a434c373c53#diff-0a743696fa43b20b718495c6353de66cR79
Дальше решил продолжить в форме обсуждения, т.к. непросто предусмотреть все варианты.

HH-101486 implement kafka listener

---

nab-kafka/pom.xml
nab-kafka/src/main/java/ru/hh/nab/kafka/monitoring/MonitoringListenStrategy.java
nab-kafka/src/main/java/ru/hh/nab/kafka/publisher/Publisher.java
nab-kafka/src/main/java/ru/hh/nab/kafka/publisher/PublisherFactory.java
nab-kafka/src/main/java/ru/hh/nab/kafka/publisher/SerializerSupplier.java
nab-kafka/src/main/java/ru/hh/nab/kafka/serialization/JacksonSerializerSupplier.java

https://jira.hh.ru/browse/HH-101492
Добавил publisher.
Убрал `topicName` из `getProducerConfig()`, т.к., судя по другим сервисам, создается один кафка темлейт, и он используется для отсылки всех сообщений. 
Пример использования в спам детекторе https://github.com/hhru/spam-detector/pull/21

HH-101492 add kafka publisher to module

---

nab-starter/pom.xml
nab-starter/src/main/java/ru/hh/nab/starter/filters/CommonHeadersFilter.java
nab-starter/src/main/java/ru/hh/nab/starter/filters/ErrorAcceptFilter.java
nab-starter/src/main/java/ru/hh/nab/starter/jersey/DefaultResourceConfig.java
nab-starter/src/main/java/ru/hh/nab/starter/server/RequestHeaders.java
nab-starter/src/main/java/ru/hh/nab/starter/server/logging/StructuredRequestLogger.java
pom.xml

Идея в том, чтобы всегда иметь возможность регулировать медиа тайп в котором должны прилетать ошибки для того, чтобы их правильно десериализовать. 
К сожалению, ошибки джерси формируются уже почле выполнения всех фильтров и для них медиатайп сбрасывается и устанавливается заново, исходя именно из Accept хэдера. 
С другой стороны джерсёвая ошибка, прилетевшая даже в правильном формате, всё равно не десериализуется в нужный нам класс ошибки, так что, возможно, этим можно пренебречь.

HH-105938 support X-HH-AcceptErrors header for custom exceptions

---

nab-common/pom.xml
nab-common/src/main/java/ru/hh/nab/common/properties/FileSettings.java
nab-data-source/pom.xml
nab-example/pom.xml
nab-hibernate/pom.xml
nab-jclient/pom.xml
nab-kafka/pom.xml
nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/Ack.java
nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/DefaultConsumerFactory.java
nab-kafka/src/main/java/ru/hh/nab/kafka/util/ConfigProvider.java
nab-logging/pom.xml
nab-metrics/pom.xml
nab-starter/pom.xml
nab-testbase/pom.xml
nab-tests/pom.xml
pom.xml

https://jira.hh.ru/browse/HH-107814
Из-за того что решили использовать свой Ack вместо спрингового Acknowledgment пропала возможность использовать методы nack которые удобно использовать для перемотки к упавшему сообщению в батче и не дублировать обработанные сообщения.
https://github.com/spring-projects/spring-kafka/blob/master/spring-kafka/src/main/java/org/springframework/kafka/support/Acknowledgment.java#L66 
Да и не совсем понятно какую цель приследовали со своим интерфейсом.

HH-107814 return Acknowledgment for kafka batch messages

---

nab-example/pom.xml
nab-hibernate/src/main/java/ru/hh/nab/hibernate/transaction/ExecuteOnDataSource.java
nab-hibernate/src/test/java/ru/hh/nab/hibernate/NabSessionFactoryBuilderFactoryTest.java
nab-starter/src/test/java/ru/hh/nab/starter/server/jetty/HHServerConnectorFailFastTest.java
nab-testbase-old/src/main/resources/service-test.properties
nab-testbase/src/main/resources/service-test.properties
nab-tests/pom.xml
nab-tests/src/test/java/ru/hh/nab/datasource/ExecuteOnDataSourceAspectTest.java
nab-tests/src/test/java/ru/hh/nab/kafka/consumer/ConsumerRecoveryAfterFailTest.java

https://jira.hh.ru/browse/HH-109743
Убрал дефолтный тип датасорса из `@ExecuteOnDataSource`.
Заодно поправил некоторые нестабильные тесты, ну и по мелочи.

HH-109743 remove default value from ExecuteOnDataSource.dataSourceType

---

nab-data-source/src/main/java/ru/hh/nab/datasource/DataSourceFactory.java
nab-data-source/src/main/java/ru/hh/nab/datasource/DataSourceSettings.java

https://jira.hh.ru/browse/HH-117779
Уменьшил validationTimeout, чтобы если первое соединение оказалось дохлым, было ещё немного времени успеть попытаться взять другое соединение.

HH-117779 decrease hikari validationTimeout

---

nab-data-source/src/main/java/ru/hh/nab/datasource/monitoring/ConnectionPoolMetrics.java
nab-data-source/src/main/java/ru/hh/nab/datasource/monitoring/NabMetricsTrackerFactory.java
nab-metrics/src/main/java/ru/hh/nab/metrics/StatsDSender.java

Изменена структура метрик БД
Было: name="hh-as.slow.connection.creation_ms"
Стало: name="jdbc_pool.connection.creation_ms", datasource="slow", app="hh-as"
Имя метрики унифицировано, а индивидуальные части каждого сервиса или БД вынесены в соответствующие тэги
Метрики старого формата передаваться не будут

HH-115873 change structure of datasource metrics

---

nab-kafka/src/main/java/ru/hh/nab/kafka/monitoring/MonitoringConsumeStrategy.java
pom.xml

https://jira.hh.ru/browse/HH-127022
Поскольку метрика "batchProcessingTimeMs" имеет тип "timer", окметр понимает, что это время, и автоматически рисует её в секундах, и суффикс "Ms" оказывается лишним.

HH-127022 remove misleading 'Ms' from metric name

---

nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/DefaultConsumerFactory.java
nab-kafka/src/main/java/ru/hh/nab/kafka/util/ConfigProvider.java
nab-testbase-old/src/main/resources/service-test.properties
nab-testbase/src/main/resources/service-test.properties

https://jira.hh.ru/browse/HH-127070
Пофиксил неправильные именования. И сделал построже проверку кафка-настроек.

HH-127070 fix naming: 'pool' -> 'poll'

---

nab-starter/pom.xml
nab-starter/src/main/java/ru/hh/nab/starter/server/cache/CacheFilter.java

Вполне реалистично, что оно тупит, т.к. там вызывается JNI, который блокирует гц, а у нас жава не может сдохнуть
В общем, если крутые пацаны из кассандры не вызывают у этой штуки close, то и нам не следует
По идее память будет в безопасности в любой случае

HH-139715 no need to explicitly stop cache

---

nab-common/src/main/java/ru/hh/nab/common/executor/MonitoredThreadPoolExecutor.java
nab-starter/src/main/java/ru/hh/nab/starter/server/jetty/MonitoredQueuedThreadPool.java

https://jira.hh.ru/browse/HH-134664
Добавил новые метрики по максимальному размеру пула для MonitoredThreadPoolExecutor и MonitoredQueuedThreadPool (Jetty). Для пула соединений с БД такая метрика уже существует.

HH-134664 Add max threads metrics to MonitoredThreadPoolExecutor and MonitoredQueuedThreadPool

---

nab-starter/src/main/java/ru/hh/nab/starter/exceptions/CompletionExceptionMapper.java
nab-starter/src/main/java/ru/hh/nab/starter/exceptions/ExceptionUtils.java
nab-starter/src/main/java/ru/hh/nab/starter/exceptions/ExecutionExceptionMapper.java
nab-starter/src/main/java/ru/hh/nab/starter/exceptions/NabMappableException.java
nab-starter/src/main/java/ru/hh/nab/starter/exceptions/UnwrappingExceptionMapper.java
nab-starter/src/main/java/ru/hh/nab/starter/exceptions/WebApplicationExceptionMapper.java
nab-starter/src/main/java/ru/hh/nab/starter/jersey/DefaultResourceConfig.java

https://jira.hh.ru/browse/HH-142977
Добавил новый unchecked эксепшн-обёртку, чтобы протаскивать checked эксепшны из http-тредов. Чтобы не добавлять маппер для этого эксепшна, заюзал джерсёвый `MappableException`, который автоматически разворачивается (но если в будущем это поведение изменится, можно будет добавить маппер).
Также добавил метод `getOrThrowMappable()` для оборачивания того, что может вылететь из `Callable` или `Future`, в этот эксепшн.
И добавил два маппера - для вытаскивания и маппинга причины из `CompletionException` и `ExecutionException`.

HH-142977 add new mappable exception and helper methods, add exception mappers

---

nab-starter/src/main/java/ru/hh/nab/starter/exceptions/NabExceptionMapper.java

As a developer in Skill team, I would like to reduce the level of client errors (as they look like WARNS for me), but still preserve the stacktrace.
* simply add new enum value;
* add new case branch.

HH-176320 | Support stacktrace for WARN level

---

nab-logging/src/main/java/ru/hh/nab/logging/HhRollingAppender.java
nab-logging/src/main/java/ru/hh/nab/logging/HhSyslogAppender.java
nab-logging/src/test/java/ru/hh/nab/logging/HhSyslogAppenderTest.java

https://jira.hh.ru/browse/HH-199975
чейнжлог:
4.43.0
компатибл фалс
Неструктурированные логи теперь будут писаться в файлы .rlog, ранее писались в .log. Для сервисов ххру важно проверить, что нету кастомных настроек для логов, например так https://github.com/search?q=org%3Ahhru+criteria.log&type=code

HH-199975 write unstructured logs to .rlog

---

nab-starter/src/main/java/ru/hh/nab/starter/filters/ErrorAcceptFilter.java

https://jira.hh.ru/browse/HH-201807
Если передан заголовок `X-HH-AcceptErrors` и статус ответа неуспешный и всё происходит под jdebug-ом, то вылетает
```
Caused by: java.lang.UnsupportedOperationException: null
at java.base/java.util.ImmutableCollections.uoe(ImmutableCollections.java:142)
at java.base/java.util.ImmutableCollections$AbstractImmutableCollection.clear(ImmutableCollections.java:149)
at javax.ws.rs.core.AbstractMultivaluedMap.putSingle(AbstractMultivaluedMap.java:74)
at ru.hh.jdebug.jersey2.provider.DebugInterceptor.lambda$aroundWriteTo$1(DebugInterceptor.java:62)
at java.base/java.util.Map.forEach(Map.java:713)
at ru.hh.jdebug.jersey2.provider.DebugInterceptor.aroundWriteTo(DebugInterceptor.java:62)
...
```
([DebugInterceptor.java:62](https://github.com/hhru/hh-java-libs/blob/ …

HH-201807 fix UnsupportedOperationException in jdebug

---

nab-starter/src/main/java/ru/hh/nab/starter/exceptions/NabExceptionMapper.java
nab-telemetry/src/test/java/ru/hh/nab/telemetry/TelemetryListenerTest.java
nab-tests/src/test/java/ru/hh/nab/starter/exceptions/CustomExceptionMappersTest.java
nab-tests/src/test/java/ru/hh/nab/starter/exceptions/NabExceptionMappersTest.java

https://jira.hh.ru/browse/HH-201052
**version change** : MINOR
**description**: if there are no any implementations of ru.hh.nab.starter.exceptions.ExceptionSerializer than exception will be mapped in NabExceptionMapper to response in common errors format 
**requires_changes_in_hh** : true
**instructions** : if you don't use any implementations of ru.hh.nab.starter.exceptions.ExceptionSerializer in your service and consumers of your service's api work with body of response that was generated in NabExceptionMapper by default serializer, you have to fix code on consumers' side

HH-201052 return common errors in exception mapper

---

nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/ConsumerBuilder.java
nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/DefaultConsumerBuilder.java
nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/DefaultConsumerFactory.java
nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/FailFastDefaultKafkaConsumerFactory.java
nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/KafkaConsumer.java
nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/KafkaConsumerFactory.java
nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/KafkaInternalTopicAck.java
nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/SimpleKafkaConsumer.java
nab-kafka/src/main/java/ru/hh/nab/kafka/monitoring/MonitoringConsumeStrategy.java
nab-telemetry-kafka/src/main/java/ru/hh/nab/telemetry/TelemetryAwareConsumerFactory.java
nab-tests/src/test/java/ru/hh/nab/kafka/consumer/KafkaConsumerTestbase.java
pom.xml

HH-214991 support builder-style for kafka consumer

---

nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/KafkaConsumer.java
nab-testbase/pom.xml
nab-testbase/src/main/java/ru/hh/nab/testbase/kafka/NoopConsumerBuilder.java
nab-testbase/src/main/java/ru/hh/nab/testbase/kafka/NoopKafkaConsumer.java
nab-testbase/src/main/java/ru/hh/nab/testbase/kafka/NoopKafkaConsumerFactory.java

HH-225900 nab-testbase: add NoopKafkaConsumerFactory

---

nab-kafka/src/main/java/ru/hh/nab/kafka/util/ConfigProvider.java
nab-metrics/pom.xml
nab-starter/src/main/java/ru/hh/nab/starter/NabProdConfig.java

1. Updated java-dogstatsd-client to 4.4.2
2. Metrics aggregation enabled by default
1. If you're using StatsDClient directly from java-statsd-client please refer to migration guide https://github.com/DataDog/java-dogstatsd-client?tab=readme-ov-file#migrating-from-2x-to-3x
2. Version 3 has only bugfixes, so migration guide is working for 2-d to 4-th version as well

HH-206867 : Bumpb statsd client to 4.4.2

---

nab-kafka/src/main/java/ru/hh/nab/kafka/util/ConfigProvider.java
nab-metrics/pom.xml
nab-starter/src/main/java/ru/hh/nab/starter/NabProdConfig.java

This reverts commit 0660c9e5453a114927dd055f2241bc4b33c169f1.
1. Downgrade java-dogstatsd-client to 2.10.5
1. If you updated to nuts-and-bolts 5.2.0 please revert changes described in instructions to earlier release

HH-226576 : Revert "HH-206867 : Bumpb statsd client to 4.4.2"

---

nab-kafka/src/main/java/ru/hh/nab/kafka/monitoring/KafkaStatsDReporter.java
nab-kafka/src/main/java/ru/hh/nab/kafka/util/ConfigProvider.java
nab-metrics/pom.xml
nab-starter/src/main/java/ru/hh/nab/starter/NabProdConfig.java

HH-227823 up statsd-client

---

nab-kafka/src/main/java/ru/hh/nab/kafka/util/ConfigProvider.java
nab-starter/src/main/java/ru/hh/nab/starter/NabProdConfig.java

HH-229623 change default statsd buffer pool size from 512 to 8

---

nab-data-source/src/main/java/ru/hh/nab/datasource/DataSourceFactory.java
nab-tests/src/test/java/ru/hh/nab/datasource/DataSourceFactoryTest.java

HH-204314 add error log on datasource creation error with db name

---

nab-common/src/main/java/ru/hh/nab/common/executor/MonitoredThreadPoolExecutor.java

HH-241042 add constants with property names to MonitoredThreadPoolExecutor

---

nab-kafka/src/main/java/ru/hh/nab/kafka/monitoring/KafkaStatsDReporter.java
nab-kafka/src/main/java/ru/hh/nab/kafka/producer/KafkaProducerFactory.java
nab-kafka/src/main/java/ru/hh/nab/kafka/util/ConfigProvider.java
nab-tests/src/test/java/ru/hh/nab/kafka/monitoring/KafkaStatsDReporterTest.java

Добавлено
- Добавлена новая опция `metrics.allowed`, которая отвечает за перечень собираемых метрик в добавок к критическим для мониторинга метрикам
- Добавлена новая опция `metrics.send-all` со значением false по умолчанию, которая отвечает за включения сбора метрик без фильтрации с помощью `metrics.allowed`

HH-241677 : Allow to filter reported metrics

---

nab-kafka/src/main/java/ru/hh/nab/kafka/util/ConfigProvider.java

Выставляем всегда enable.auto.commit=false в kafka-consumer-ах, оставляя возможность заоверрайдить это в конфиге на true.
с некоторой вероятностью это также делает spring-kafka уже внутри при выставлении `containerProperties.setAckMode(ContainerProperties.AckMode.MANUAL_IMMEDIATE);`, но не хочется на это полагаться.
Сейчас эта настройка кочует из конфига в конфиг в deploy и иногда может потеряться.

HH-243521 default enable-auto-commit=false in nab-kafka

---

nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/DefaultConsumerBuilder.java
nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/RetryService.java
nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/retry/HeadersMessageMetadataProvider.java
nab-kafka/src/test/java/ru/hh/nab/kafka/consumer/RetryServiceTest.java
nab-kafka/src/test/java/ru/hh/nab/kafka/consumer/retry/HeadersMessageMetadataProviderTest.java

HH-240171: nab-kafka: add `x-retry-receive-topic` header needed by kafka-retry-service
