hhru/nuts-and-bolts

- nuts-and-bolts/pom.xml
- pom.xml
Перевод nab на hibernate4 и другие вещи для работы с java8.
> HH-51389 prepare nab to be used with java8

- example-app/pom.xml
- nuts-and-bolts/pom.xml
- nuts-and-bolts/src/main/java/ru/hh/nab/JerseyGutsModule.java
- nuts-and-bolts/src/main/java/ru/hh/nab/grizzly/SimpleGrizzlyAdapterChain.java
- nuts-and-bolts/src/main/java/ru/hh/nab/grizzly/SimpleGrizzlyWebServer.java
- nuts-and-bolts/src/main/java/ru/hh/nab/grizzly/monitoring/MarkableProbe.java
- nuts-and-bolts/src/main/java/ru/hh/nab/grizzly/monitoring/NabConnectionProbe.java
- nuts-and-bolts/src/main/java/ru/hh/nab/health/monitoring/MethodProbingInterceptor.java
- nuts-and-bolts/src/main/java/ru/hh/nab/jersey/JerseyHttpHandler.java
- pom.xml
Тайминги для стадий TCP в гриззли
> HH-51048 add tcp timings

- nuts-and-bolts/src/main/java/ru/hh/nab/grizzly/MemoryManagerFactory.java
- nuts-and-bolts/src/main/java/ru/hh/nab/grizzly/SimpleGrizzlyWebServer.java
- nuts-and-bolts/src/test/java/ru/hh/nab/grizzly/MemoryManagerFactoryTest.java
https://jira.hh.ru/browse/HH-51900
> HH-51900 add memory manager settings

- nuts-and-bolts/src/main/java/ru/hh/nab/grizzly/SimpleGrizzlyAdapterChain.java
https://jira.hh.ru/browse/HH-52630
> HH-52630 fix NullPointerException in SimpleGrizzlyAdapterChain

- nuts-and-bolts/pom.xml
- nuts-and-bolts/src/main/java/ru/hh/nab/JerseyGutsModule.java
- nuts-and-bolts/src/main/java/ru/hh/nab/NabModule.java
- nuts-and-bolts/src/main/java/ru/hh/nab/grizzly/monitoring/MarkableProbe.java
- pom.xml
https://jira.hh.ru/browse/HH-52963
> HH-52963 update c3p0 version and prepare for monitoring

- nuts-and-bolts/src/main/java/ru/hh/nab/grizzly/GrizzletHandler.java
- nuts-and-bolts/src/main/java/ru/hh/nab/grizzly/RequestHandler.java
- nuts-and-bolts/src/main/java/ru/hh/nab/grizzly/SimpleGrizzlyAdapterChain.java
- pom.xml
https://jira.hh.ru/browse/HH-53574
> HH-53574 add response status to timings

- pom.xml
https://jira.hh.ru/browse/HH-59034
> HH-59034 update timings version which is now public

- nuts-and-bolts/pom.xml
- nuts-and-bolts/src/main/java/ru/hh/nab/jetty/JettyServerFactory.java
- pom.xml
https://jira.hh.ru/browse/HH-61483
> HH-61483 shutdown gracefully

- nuts-and-bolts/pom.xml
- nuts-and-bolts/src/main/java/ru/hh/nab/Launcher.java
https://jira.hh.ru/browse/HH-64033
> HH-64033 remove all jul handlers

- nuts-and-bolts/pom.xml
- nuts-and-bolts/src/main/java/ru/hh/nab/jetty/JettyServerFactory.java
https://jira.hh.ru/browse/HH-64713
> HH-64713 use jetty fail fast

- nuts-and-bolts/pom.xml
- nuts-and-bolts/src/main/java/ru/hh/nab/MonitoringDataSourceProvider.java
- nuts-and-bolts/src/main/java/ru/hh/nab/NabModule.java
- nuts-and-bolts/src/main/java/ru/hh/nab/jersey/JerseyResourceFilterFactory.java
- nuts-and-bolts/src/main/java/ru/hh/nab/jersey/RequestUrlFilter.java
- nuts-and-bolts/src/test/java/ru/hh/nab/async/GuicyAsyncExecutorTest.java
- nuts-and-bolts/src/test/java/ru/hh/nab/hibernate/PersistenceTest.java
Добавил мониторинг базы данных
https://jira.hh.ru/browse/HH-66918
> HH-66918 add db source monitoring

- nuts-and-bolts/pom.xml
- nuts-and-bolts/src/main/java/ru/hh/nab/hibernate/Transactional.java
- nuts-and-bolts/src/main/java/ru/hh/nab/hibernate/TransactionalContext.java
- nuts-and-bolts/src/main/java/ru/hh/nab/hibernate/TxInterceptor.java
https://jira.hh.ru/browse/HH-67729
> HH-67729 do not open real transaction for readonly transaction

- example-app/pom.xml
- nuts-and-bolts/pom.xml
- nuts-and-bolts/src/main/java/ru/hh/nab/hibernate/Transactional.java
- nuts-and-bolts/src/main/java/ru/hh/nab/hibernate/TransactionalContext.java
- nuts-and-bolts/src/main/java/ru/hh/nab/hibernate/TxInterceptor.java
- pom.xml
Задепрекейтил optional в transactional
https://jira.hh.ru/browse/HH-67965
> HH-67965 deprecate optional flag of @Transactional

- nuts-and-bolts/pom.xml
- nuts-and-bolts/src/main/java/ru/hh/nab/MonitoringDataSourceProvider.java
Обновил версию hh-metrics
https://jira.hh.ru/browse/HH-67822
> HH-67822 update hh-metrics version

- nuts-and-bolts/pom.xml
- nuts-and-bolts/src/main/java/ru/hh/nab/MonitoringDataSourceProvider.java
https://jira.hh.ru/browse/HH-68329
> HH-68329 add monitoring of db connection usage with stack traces

- nuts-and-bolts/pom.xml
https://jira.hh.ru/browse/HH-68490
> HH-68490 update hh-metrics

- nuts-and-bolts/src/main/java/ru/hh/nab/MonitoringDataSourceProvider.java
https://jira.hh.ru/browse/HH-68552
> HH-68552 remove TransactionalContext from compressed stacks of db connection usage

- example-app/src/etc/example-app/settings.properties
- nuts-and-bolts/src/main/java/ru/hh/nab/MonitoringDataSourceProvider.java
- nuts-and-bolts/src/main/java/ru/hh/nab/SettingsModule.java
- nuts-and-bolts/src/test/java/ru/hh/nab/async/GuicyAsyncExecutorTest.java
- nuts-and-bolts/src/test/java/ru/hh/nab/hibernate/PersistenceTest.java
https://jira.hh.ru/browse/HH-68647
> HH-68647 add mandatory serviceName property, use it as prefix in db metrics

- nuts-and-bolts/src/main/java/ru/hh/nab/NabModule.java
- nuts-and-bolts/src/test/java/ru/hh/nab/security/SecureResourceWithExplicitAnonymousTest.java
- nuts-and-bolts/src/test/java/ru/hh/nab/security/SecureResourceWithImplicitAnonymousTest.java
- nuts-and-bolts/src/test/java/ru/hh/nab/xml/XmlSanitizingTest.java
- nuts-and-bolts/src/test/java/ru/hh/util/AcceptHeaderFixTest.java
Разделили бин StatsDSender на бины StatsDClient, ScheduledExecutor и StatsDSender
https://jira.hh.ru/browse/HH-69206
> HH-69206 split StatsDSender on StatsDClient, ScheduledExecutor and StatsDSender

- nuts-and-bolts/src/main/java/ru/hh/nab/MonitoringDataSourceProvider.java
https://jira.hh.ru/browse/HH-69159
> HH-69159 check database before start service

- nab-hibernate/pom.xml
- nab-hibernate/src/main/java/ru/hh/nab/hibernate/DebugInitializer.java
- nab-hibernate/src/main/java/ru/hh/nab/hibernate/HibernateModule.java
- nuts-and-bolts/pom.xml
- nuts-and-bolts/src/main/java/ru/hh/nab/AppMetadata.java
- nuts-and-bolts/src/main/java/ru/hh/nab/DebugInitializer.java
- nuts-and-bolts/src/main/java/ru/hh/nab/DebugModule.java
- nuts-and-bolts/src/main/java/ru/hh/nab/NabModule.java
- nuts-and-bolts/src/main/java/ru/hh/nab/StatusResource.java
- pom.xml
https://jira.hh.ru/browse/HH-71495
> HH-71495 Add jdebug and jdbc debug to nab

- example-app/pom.xml
- example-app/src/test/java/ru/hh/nab/example/GuicyAsyncExecutorTest.java
- example-app/src/test/java/ru/hh/nab/example/PersistenceTest.java
- nab-hibernate/pom.xml
- nab-hibernate/src/main/java/ru/hh/nab/hibernate/DataSourceProvider.java
- nab-hibernate/src/main/java/ru/hh/nab/hibernate/HibernateModule.java
https://jira.hh.ru/browse/HH-71843
> HH-71843 add StatementTimeoutDataSource

- nuts-and-bolts/src/main/java/ru/hh/nab/Launcher.java
https://jira.hh.ru/browse/HH-72642
> HH-72642 init settings into named strings in test mode

- nab-core/src/main/java/ru/hh/nab/core/jetty/JettyFactory.java
Добавил возможность использовать сессии джетти
https://jira.hh.ru/browse/HH-77467
> HH-77467 add ability to use sessions

- nab-data-source/pom.xml
- nab-data-source/src/main/java/ru/hh.nab/datasource/postgres/embedded/EmbeddedPostgresDataSourceFactory.java
- nab-data-source/src/test/java/ru/hh/nab/datasource/jdbc/MonitoringDataSourceTest.java
- nab-hibernate/src/test/java/ru/hh/nab/hibernate/HibernateTestBase.java
- nab-hibernate/src/test/java/ru/hh/nab/hibernate/HibernateTestBaseConfig.java
- nab-hibernate/src/test/java/ru/hh/nab/hibernate/transaction/DataSourceContextTest.java
- nab-hibernate/src/test/java/ru/hh/nab/hibernate/transaction/DataSourceContextTransactionManagerTest.java
- nab-hibernate/src/test/java/ru/hh/nab/hibernate/transaction/ExecuteOnDataSourceAspectTest.java
- pom.xml
Засинкал EmbeddedPGDSFactory с имплементацией в ххру (Гриша недавно вносил изменения). И поправил тесты, чтобы использоавли единый контекст, т.к. теперь они начали падать если поднимается несколько инстансов базы.
> HH-79285 sync EmbeddedPGDSFactory and fix tests

- nab-common/pom.xml
- nab-core/src/main/resources/nab-shared-logback.xml
https://jira.hh.ru/browse/HH-77884
> HH-77884 removed nab-shared-logback.xml from nab-core

- .travis.yml
- pom.xml
https://jira.hh.ru/browse/HH-79903
> HH-79903 fix coveralls reporting

- nab-hibernate/src/main/java/ru/hh/nab/hibernate/transaction/DataSourceContext.java
- nab-hibernate/src/main/java/ru/hh/nab/hibernate/transaction/DataSourceContextUnsafe.java
чтобы можно было их заиспользовать в ххру
> HH-80039 make some nab-hibernate methods public

- nab-common/pom.xml
- nab-common/src/test/java/ru/hh/nab/common/mdc/MDCTest.java
- nab-common/src/test/java/ru/hh/nab/common/properties/FileSettingsTest.java
- nab-core/pom.xml
- nab-core/src/main/java/ru/hh/nab/core/CoreCommonConfig.java
- nab-core/src/main/java/ru/hh/nab/core/CoreProdConfig.java
- nab-core/src/main/java/ru/hh/nab/core/jetty/JettyFactory.java
- nab-core/src/test/java/ru/hh/nab/core/CoreTestConfig.java
- nab-core/src/test/java/ru/hh/nab/core/LauncherTest.java
- nab-data-source/pom.xml
- nab-data-source/src/test/java/ru/hh/nab/datasource/CompressedStackFactoryTest.java
- nab-data-source/src/test/java/ru/hh/nab/datasource/DataSourceTestConfig.java
- nab-data-source/src/test/java/ru/hh/nab/datasource/JdbcTemplateTest.java
- nab-data-source/src/test/java/ru/hh/nab/datasource/jdbc/MonitoringDataSourceTest.java
- nab-testbase/pom.xml
- pom.xml
https://jira.hh.ru/browse/HH-79748
- Ограничивать размер очереди настройкой maxThreads
- Добавил тесты
> HH-79748 use bounded queue for jetty thread pool and nab-tests

- nab-hibernate/src/main/java/ru/hh/nab/hibernate/HibernateCommonConfig.java
- nab-hibernate/src/main/java/ru/hh/nab/hibernate/MappingConfig.java
- nab-hibernate/src/main/java/ru/hh/nab/hibernate/NabSessionFactoryBean.java
- nab-hibernate/src/main/java/ru/hh/nab/hibernate/NabSessionFactoryBuilderFactory.java
- nab-hibernate/src/test/java/ru/hh/nab/hibernate/HibernateTestBaseConfig.java
- nab-hibernate/src/test/java/ru/hh/nab/hibernate/MappingConfigTest.java
- nab-hibernate/src/test/java/ru/hh/nab/hibernate/model/TestEntity.java
- nab-hibernate/src/test/java/ru/hh/nab/hibernate/model/test/PackageScanEntity.java
- nab-hibernate/src/test/java/ru/hh/nab/hibernate/transaction/DataSourceContextTransactionManagerTest.java
https://jira.hh.ru/browse/HH-77163
> HH-77163 support packagesToScan for hibernate session factory

- README.md
Мы ничего не гарантируем для пользователей, не имеющих отношения к HH
Проект никак не лицензирован и открыт только для возможности его использования студентами и подрядчиками
Мы не берем на себя никаких гарантий по поддержке, кроме наших внутренних нужд
Про это надо написать, а то кто-нибудь заюзает и будет плакать потом
> HH-80608 add explanation for potential external users

- nab-example/pom.xml
- nab-example/src/test/java/ru/hh/nab/example/ExampleResourceTest.java
- nab-testbase/src/main/java/ru/hh/nab/testbase/NabTestBase.java
https://jira.hh.ru/browse/HH-81251
HH-81251 Add example for resource testing
> HH-81251 Add example for resource testing

- nab-data-source/src/main/java/ru/hh/nab/datasource/DataSourceFactory.java
- nab-data-source/src/main/java/ru/hh/nab/datasource/monitoring/MonitoringDataSourceFactory.java
- nab-data-source/src/main/java/ru/hh/nab/datasource/monitoring/stack/CompressedStackFactory.java
- nab-data-source/src/main/java/ru/hh/nab/datasource/monitoring/stack/CompressedStackFactoryConfig.java
- nab-data-source/src/main/java/ru/hh/nab/datasource/monitoring/stack/CompressedStackFactoryDefaults.java
- nab-data-source/src/test/java/ru/hh/nab/datasource/monitoring/CompressedStackFactoryTest.java
- nab-example/src/main/java/ru/hh/nab/example/ExampleConfig.java
- nab-example/src/main/java/ru/hh/nab/example/ExampleMain.java
- nab-example/src/main/java/ru/hh/nab/example/ExampleResource.java
- nab-starter/src/main/java/ru/hh/nab/starter/NabApplicationContext.java
- nab-testbase/src/main/java/ru/hh/nab/testbase/JettyTestContainerFactory.java
- nab-testbase/src/main/java/ru/hh/nab/testbase/NabTestBase.java
https://jira.hh.ru/browse/HH-81799
> HH-81799 add compressed stack config

- nab-common/src/main/java/ru/hh/nab/common/properties/PropertiesUtils.java
- nab-common/src/test/java/ru/hh/nab/common/properties/PropertiesUtilsTest.java
- nab-starter/src/main/java/ru/hh/nab/starter/NabCommonConfig.java
- nab-starter/src/main/java/ru/hh/nab/starter/NabProdConfig.java
- nab-starter/src/main/java/ru/hh/nab/starter/server/jetty/JettyServerFactory.java
- nab-starter/src/test/java/ru/hh/nab/starter/NabProdConfigTest.java
- nab-testbase/src/main/java/ru/hh/nab/testbase/NabTestConfig.java
https://jira.hh.ru/browse/HH-81279
> HH-81279 improve datacenter support

- nab-starter/src/main/java/ru/hh/nab/starter/AppMetadata.java
- nab-starter/src/main/java/ru/hh/nab/starter/NabApplication.java
- nab-starter/src/main/java/ru/hh/nab/starter/NabCommonConfig.java
- nab-starter/src/main/java/ru/hh/nab/starter/NabServletContextConfig.java
- nab-starter/src/main/java/ru/hh/nab/starter/server/jetty/JettyWebAppContext.java
- nab-tests/pom.xml
- nab-tests/src/test/java/ru/hh/nab/starter/NabApplicationTest.java
- nab-tests/src/test/resources/project.properties
Тест /status
Тест надежного падения
Рефакторинг appMetadata
> HH-81790 NaB improvements

- nab-example/src/test/java/ru/hh/nab/example/ExampleResourceTest.java
- nab-example/src/test/java/ru/hh/nab/example/ExampleServerAwareBeanTest.java
- nab-example/src/test/java/ru/hh/nab/example/ExampleTestConfig.java
- nab-hibernate/src/main/java/ru/hh/nab/hibernate/datasource/RoutingDataSource.java
- nab-hibernate/src/main/java/ru/hh/nab/hibernate/routing/DataSourceRoutingFilter.java
- nab-hibernate/src/main/java/ru/hh/nab/hibernate/transaction/DataSourceContext.java
- nab-hibernate/src/main/java/ru/hh/nab/hibernate/transaction/DataSourceContextTransactionManager.java
- nab-hibernate/src/main/java/ru/hh/nab/hibernate/transaction/DataSourceContextUnsafe.java
- nab-hibernate/src/main/java/ru/hh/nab/hibernate/transaction/ExecuteOnDataSource.java
- nab-hibernate/src/main/java/ru/hh/nab/hibernate/transaction/ExecuteOnDataSourceAspect.java
- nab-starter/src/test/java/ru/hh/nab/starter/server/jetty/HHServerConnectorFailFastTest.java
- nab-testbase/src/main/java/ru/hh/nab/testbase/NabTestConfig.java
- nab-testbase/src/main/resources/service-test.properties
- nab-tests/src/test/java/ru/hh/nab/hibernate/DataSourceSwitchingTest.java
- nab-tests/src/test/java/ru/hh/nab/hibernate/transaction/DataSourceContextTest.java
- nab-tests/src/test/java/ru/hh/nab/hibernate/transaction/DataSourceContextTransactionManagerTest.java
- nab-tests/src/test/java/ru/hh/nab/hibernate/transaction/DataSourceContextUnsafeTest.java
- nab-tests/src/test/java/ru/hh/nab/hibernate/transaction/ExecuteOnDataSourceAspectTest.java
with dataSourceKey provided in request
> HH-87944 allow to override dataSourceKey 

- nab-common/pom.xml
- nab-data-source/pom.xml
- nab-data-source/src/main/java/ru/hh/nab/datasource/DataSourceFactory.java
- nab-example/pom.xml
- nab-hibernate/pom.xml
- nab-logging/pom.xml
- nab-starter/pom.xml
- nab-testbase/pom.xml
- nab-tests/pom.xml
- pom.xml
https://jira.hh.ru/browse/HH-88551
> HH-88551 add ability to set HikariConfig in DataSourceFactory

- nab-starter/src/main/resources/nab-shared-logback.xml
https://jira.hh.ru/browse/HH-88625
> HH-88625 Move library logs to libraries.log :)

- .travis.yml
- README.md
- pom.xml
https://jira.hh.ru/browse/HH-89339
> HH-89339 Add SonarCloud integration

- pom.xml
https://jira.hh.ru/browse/HH-89951
Поднимаю версию hamcrest до 2.1
> HH-89951 Up hamcrest to 2.1

- nab-starter/src/main/java/ru/hh/nab/starter/server/jetty/JettyServer.java
https://jira.hh.ru/browse/HH-92322
> HH-92322 allow to configure some settings

- nab-hibernate/src/main/java/ru/hh/nab/hibernate/transaction/ExecuteOnDataSourceAspect.java
https://jira.hh.ru/browse/HH-93342
> HH-93342 fix writableTx propagation

- nab-metrics/src/main/java/ru/hh/nab/metrics/Histogram.java
https://jira.hh.ru/browse/HH-96657
> HH-96657 need histogram for search

- nab-logging/src/main/java/ru/hh/nab/logging/NabLoggingConfiguratorTemplate.java
https://jira.hh.ru/browse/HH-97513
> HH-97513 public api for logback jmxconfigurator

- nab-hibernate/src/main/java/ru/hh/nab/hibernate/NabHibernateCommonConfig.java
- nab-hibernate/src/main/java/ru/hh/nab/hibernate/routing/DataSourceRoutingFilter.java
- nab-hibernate/src/main/java/ru/hh/nab/hibernate/transaction/DataSourceContext.java
- nab-hibernate/src/main/java/ru/hh/nab/hibernate/transaction/TransactionalScope.java
- nab-hibernate/src/test/java/ru/hh/nab/hibernate/routing/DataSourceRoutingFilterTest.java
- nab-jclient/src/main/java/ru/hh/nab/jclient/checks/TransactionalCheck.java
- nab-tests/src/test/java/ru/hh/jclient/common/JClientTransactionTest.java
- nab-tests/src/test/java/ru/hh/nab/hibernate/DataSourceSwitchingTest.java
- nab-tests/src/test/java/ru/hh/nab/hibernate/transaction/DataSourceContextTest.java
https://jira.hh.ru/browse/HH-98211
> HH-98211 create transactional scope

- nab-common/pom.xml
- nab-data-source/pom.xml
- nab-example/pom.xml
- nab-hibernate/pom.xml
- nab-jclient/pom.xml
- nab-logging/pom.xml
- nab-logging/src/main/java/ru/hh/nab/logging/NabLoggingConfiguratorTemplate.java
- nab-metrics/pom.xml
- nab-starter/pom.xml
- nab-testbase/pom.xml
- nab-tests/pom.xml
- pom.xml
https://jira.hh.ru/browse/HH-99456
> HH-99456 Add ability to override or add loggers via properties

- nab-jclient/src/main/java/ru/hh/nab/jclient/NabJClientConfig.java
- nab-jclient/src/main/java/ru/hh/nab/jclient/UriCompactionUtil.java
- nab-tests/src/test/java/ru/hh/nab/jclient/UriCompactionUtilTest.java
- pom.xml
Этот кусок говна призван сжимать переменные части урлов для лучшей группировки. Поскольку только мы знаем какие у нас бывают переменные куски, то эта логика живет здесь.
работает негарантированно, но достаточно хорошо. все хэши за 13 часов 20.10.2019 подошли под эвристику
> HH-99838 introduce url compaction function and up dependencies

- nab-starter/src/main/java/ru/hh/nab/starter/NabServletContextConfig.java
- nab-starter/src/main/java/ru/hh/nab/starter/server/jetty/ChannelsReadyChecker.java
- pom.xml
https://jira.hh.ru/browse/HH-101519
> HH-101519 update jetty

- nab-starter/src/main/java/ru/hh/nab/starter/NabServletContextConfig.java
- nab-starter/src/main/java/ru/hh/nab/starter/server/jetty/ChannelsReadyChecker.java
- pom.xml
This reverts commit fe212d2261507bb0df6b60c8334b1f3cb14e9f5e.
> Revert "HH-101519 update jetty"

- nab-kafka/pom.xml
- nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/DefaultListenerFactory.java
- nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/ListenStrategy.java
- nab-kafka/src/main/java/ru/hh/nab/kafka/monitoring/MonitoringListenStrategy.java
https://jira.hh.ru/browse/HH-101491
1. Добавил KafkaStatsDReporter (если его нет в контексте - не беда, не падаем)
2. добавил время обработки батча
2.1. хотел по красоте как-н сделать, через тот же KafkaStatsDReporter подсунуть, но не вышло - у MetricsReporter неудачный контракт
2.2. думал подсунуть через micrometer https://docs.spring.io/spring-kafka/docs/2.3.3.RELEASE/reference/html/#micrometer но получается тоже не очень
2.3. поэтому сделал влоб с помощью обертки
> HH-101491 add statsD monitoring for kafka

- nab-kafka/pom.xml
- nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/DefaultListenerFactory.java
- nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/ListenerGroupId.java
- nab-kafka/src/main/java/ru/hh/nab/kafka/monitoring/MonitoringListenStrategy.java
https://jira.hh.ru/browse/HH-102015
Криво замерял время.
Воспользовался библиотечкой timings
> HH-102015 fix batchProcessingTimeMs monitoring

- nab-kafka/README.md
https://jira.hh.ru/browse/HH-104463
> HH-104463 add README.md for nab-kafka module

- nab-kafka/src/main/java/ru/hh/nab/kafka/producer/DefaultKafkaProducer.java
- nab-kafka/src/main/java/ru/hh/nab/kafka/producer/KafkaProducer.java
- nab-kafka/src/main/java/ru/hh/nab/kafka/producer/KafkaProducerFactory.java
- nab-kafka/src/main/java/ru/hh/nab/kafka/producer/KafkaSendResult.java
- nab-tests/src/test/java/ru/hh/nab/kafka/producer/ProducerFactoryTest.java
https://jira.hh.ru/browse/HH-104397
> HH-104397 remove generification from KafkaProducer interface

- nab-testbase/pom.xml
https://jira.hh.ru/browse/HH-106525
> HH-106525 bump kafka-test-utils to 0.0.7

- nab-kafka/src/main/java/ru/hh/nab/kafka/producer/DefaultKafkaProducer.java
- nab-kafka/src/main/java/ru/hh/nab/kafka/producer/KafkaProducer.java
- nab-tests/src/test/java/ru/hh/nab/kafka/producer/ProducerFactoryTest.java
https://jira.hh.ru/browse/HH-106719
> HH-106719 kafka publisher without message class parameter

- nab-kafka/src/main/java/ru/hh/nab/kafka/producer/DefaultKafkaProducer.java
https://jira.hh.ru/browse/HH-106992
> HH-106992 send kafka messages async

- nab-jclient/src/main/java/ru/hh/nab/jclient/JClientContextProviderFilter.java
- nab-tests/src/test/java/ru/hh/nab/jclient/JClientContextProviderFilterTest.java
https://jira.hh.ru/browse/HH-107064
> HH-107064 cath IllegalArgumentException in JClientContextProviderFilter

- .hh-release.yaml
https://jira.hh.ru/browse/HH-108984
> HH-108984 add .hh-release.yaml

- nab-kafka/src/main/java/ru/hh/nab/kafka/producer/DefaultKafkaProducer.java
https://jira.hh.ru/browse/HH-109116
> HH-109116 add overload method send with Executor

- nab-kafka/src/main/java/ru/hh/nab/kafka/producer/DefaultKafkaProducer.java
- nab-kafka/src/main/java/ru/hh/nab/kafka/producer/KafkaProducer.java
https://jira.hh.ru/browse/HH-109319
> HH-109319 add send with executor versions to interface KafkaProducer

- nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/DefaultConsumerFactory.java
- nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/DeserializerSupplier.java
- nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/FailFastDefaultKafkaConsumerFactory.java
- nab-kafka/src/main/java/ru/hh/nab/kafka/util/ConfigProvider.java
https://jira.hh.ru/browse/HH-109543
> HH-109543 make fail-fast kafka consumer

- nab-kafka/src/main/java/ru/hh/nab/kafka/util/ConfigProvider.java
- nab-kafka/src/test/java/ru/hh/nab/kafka/util/ConfigProviderTest.java
https://jira.hh.ru/browse/HH-112089
> HH-112089 do not start kafka consumer if found unused properties

- nab-kafka/src/main/java/ru/hh/nab/kafka/producer/KafkaProducerFactory.java
- nab-tests/src/test/java/ru/hh/nab/kafka/consumer/ConsumerRecoveryAfterFailTest.java
https://jira.hh.ru/browse/HH-113352
> HH-113352 request cluster metadata before producer start

- nab-starter/src/main/java/ru/hh/nab/starter/NabApplication.java
- nab-starter/src/main/java/ru/hh/nab/starter/logging/LogLevelOverrideApplier.java
- nab-starter/src/main/java/ru/hh/nab/starter/logging/LogLevelOverrideExtension.java
- nab-testbase-old/src/main/java/ru/hh/nab/testbase/old/NabTestBase.java
https://jira.hh.ru/browse/HH-113445
> HH-113445 add LogLevelOverrideExtension

- nab-kafka/pom.xml
https://jira.hh.ru/browse/HH-113949
добавили новые метрики
> HH-113949 up kafka-client-utils

- nab-starter/src/main/java/ru/hh/nab/starter/ConsulService.java
- nab-starter/src/main/java/ru/hh/nab/starter/NabProdConfig.java
- nab-tests/src/test/java/ru/hh/nab/starter/NabAppTestConfig.java
https://jira.hh.ru/browse/HH-114285
> HH-114285 add consul tag if service implement LogLevelOverrideExtension

- nab-example/pom.xml
- nab-starter/src/main/java/ru/hh/nab/starter/NabCommonConfig.java
- nab-testbase/pom.xml
- nab-testbase/src/main/java/ru/hh/nab/testbase/listeners/TestExecutorListener.java
- nab-testbase/src/main/java/ru/hh/nab/testbase/listeners/dto/ResultStatus.java
- nab-testbase/src/main/java/ru/hh/nab/testbase/listeners/dto/StandType.java
- nab-testbase/src/main/java/ru/hh/nab/testbase/listeners/dto/TestExecResult.java
https://jira.hh.ru/browse/HH-118126
> HH-118126 add TestExecutorListener

- nab-testbase/src/main/java/ru/hh/nab/testbase/extensions/NabJunitWebConfig.java
- nab-testbase/src/main/java/ru/hh/nab/testbase/extensions/SpringContextStatusCheckExtension.java
https://jira.hh.ru/browse/HH-120376
> HH-120376 add fail fast extension

- nab-starter/src/main/java/ru/hh/nab/starter/server/RequestHeaders.java
- nab-starter/src/main/java/ru/hh/nab/starter/server/logging/StructuredRequestLogger.java
В файлбите там вроде вайтлист - так что не должно поломаться
https://github.com/hhru/deploy-dev/blob/master/public/playbooks/roles/hh-filebeat/templates/etc/filebeat/filebeat.yml#L140
В элмо добавить не так просто - надо колонку добавлять в кх. отдельной задачей надо делать
> HH-121055 add userAgent to request log

- nab-testbase/src/main/java/ru/hh/nab/testbase/TestLogbackBaseConfigurator.java
- pom.xml
https://jira.hh.ru/browse/HH-122125
Исправил кое-какие нюансы в логгировании.
> HH-122125 tune unit-test logging

- nab-testbase/src/main/java/ru/hh/nab/testbase/listeners/TestExecutorListener.java
https://jira.hh.ru/browse/HH-122335
> HH-122335 fix long db connection timeout for some users in TestExecutorListener

- nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/ConsumeStrategy.java
- nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/KafkaConsumer.java
- nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/KafkaInternalTopicAck.java
- nab-kafka/src/main/java/ru/hh/nab/kafka/monitoring/MonitoringConsumeStrategy.java
- nab-tests/src/test/java/ru/hh/nab/kafka/consumer/ConsumerRecoveryAfterFailTest.java
https://jira.hh.ru/browse/HH-123682
> HH-123682 nab kafka commit records per-partition

- nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/Ack.java
- nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/KafkaConsumer.java
- nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/KafkaInternalTopicAck.java
- nab-tests/src/test/java/ru/hh/nab/kafka/consumer/ConsumerRecoveryAfterFailTest.java
https://jira.hh.ru/browse/HH-123739﻿
> HH-123739 batch ack handler for nab-kafka

- nab-common/src/main/java/ru/hh/nab/common/cache/PartiallyOverflowingCache.java
- nab-starter/src/main/java/ru/hh/nab/starter/jersey/MarshallerContextResolver.java
- nab-tests/pom.xml
- nab-tests/src/test/java/ru/hh/nab/performance/PartiallyOverflowingCachePerformanceTest.java
- nab-tests/src/test/java/ru/hh/nab/performance/variants/GenericCache.java
- nab-tests/src/test/java/ru/hh/nab/performance/variants/PartiallyOverflowingCache.java
- nab-tests/src/test/java/ru/hh/nab/performance/variants/PartiallyOverflowingCacheOptional.java
- nab-tests/src/test/java/ru/hh/nab/performance/variants/PartiallyOverflowingCacheWithSizeAtomicCache.java
- nab-tests/src/test/java/ru/hh/nab/performance/variants/PartiallyOverflowingCacheWithSizeCache.java
задача https://jira.hh.ru/browse/HH-127076
> HH-127076 move DoubleStorageCache to nab

- nab-hibernate/pom.xml
- nab-logging/pom.xml
- nab-starter/pom.xml
- nab-starter/src/main/java/ru/hh/nab/starter/ConsulService.java
- nab-starter/src/main/java/ru/hh/nab/starter/NabProdConfig.java
- nab-testbase-old/pom.xml
- nab-testbase/pom.xml
- nab-tests/src/test/java/ru/hh/nab/starter/ConsulServiceTest.java
- pom.xml
> HH-128241 consul up

- nab-starter/src/main/java/ru/hh/nab/starter/server/logging/StructuredRequestLogger.java
https://jira.hh.ru/browse/HH-129612
> HH-129612 add positive check for outerTimoutMs

- nab-jclient/src/main/java/ru/hh/nab/jclient/UriCompactionUtil.java
- nab-telemetry/pom.xml
- nab-telemetry/src/main/java/ru/hh/nab/telemetry/NabTelemetryConfig.java
- nab-telemetry/src/main/java/ru/hh/nab/telemetry/TelemetryFilter.java
- nab-telemetry/src/main/java/ru/hh/nab/telemetry/TelemetryListenerImpl.java
- nab-telemetry/src/main/java/ru/hh/nab/telemetry/TelemetryProcessorFactory.java
- nab-tests/src/test/java/ru/hh/jclient/common/TelemetryTest.java
HH-129651 fix for operation name
> HH-129651 fix for operation name

- nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/KafkaConsumer.java
- nab-tests/src/test/java/ru/hh/nab/kafka/consumer/ConsumerRecoveryAfterFailTest.java
https://jira.hh.ru/browse/HH-135808
> HH-135808 initial value for wholeBatchCommited

- pom.xml
https://jira.hh.ru/browse/HH-139987
Надо для jdk 17
> HH-139987 up hibernate

- nab-common/pom.xml
- nab-common/src/main/java/ru/hh/nab/common/qualifier/NamedQualifier.java
- nab-data-source/src/main/java/ru/hh/nab/datasource/NabDataSourceProdConfig.java
- nab-hibernate/src/main/java/ru/hh/nab/hibernate/NabHibernateCommonConfig.java
- nab-hibernate/src/main/java/ru/hh/nab/hibernate/NabHibernateProdConfig.java
- nab-hibernate/src/main/java/ru/hh/nab/hibernate/NabSessionFactoryBean.java
- nab-hibernate/src/main/java/ru/hh/nab/hibernate/qualifier/Hibernate.java
- nab-jclient/src/main/java/ru/hh/nab/jclient/NabJClientConfig.java
- nab-starter/pom.xml
- nab-starter/src/main/java/ru/hh/nab/starter/ConsulService.java
- nab-starter/src/main/java/ru/hh/nab/starter/NabApplication.java
- nab-starter/src/main/java/ru/hh/nab/starter/NabCommonConfig.java
- nab-starter/src/main/java/ru/hh/nab/starter/NabProdConfig.java
- nab-starter/src/main/java/ru/hh/nab/starter/jersey/MarshallerContextResolver.java
- nab-starter/src/main/java/ru/hh/nab/starter/qualifier/Service.java
- nab-starter/src/test/java/ru/hh/nab/starter/NabProdConfigTest.java
- nab-telemetry/src/main/java/ru/hh/nab/telemetry/NabTelemetryConfig.java
- nab-testbase-old/src/main/java/ru/hh/nab/testbase/old/hibernate/NabHibernateTestBaseConfig.java
- nab-testbase/src/main/java/ru/hh/nab/testbase/NabTestConfig.java
- nab-testbase/src/main/java/ru/hh/nab/testbase/hibernate/NabHibernateTestBaseConfig.java
- nab-testbase/src/main/java/ru/hh/nab/testbase/listeners/TestExecutorListener.java
- nab-tests/src/test/java/ru/hh/nab/kafka/KafkaTestConfig.java
- nab-tests/src/test/java/ru/hh/nab/starter/ConsulServiceTest.java
- nab-tests/src/test/java/ru/hh/nab/starter/NabApplicationTest.java
- nab-tests/src/test/java/ru/hh/nab/starter/ServletTest.java
https://jira.hh.ru/browse/HH-142710
> HH-142710 add qualifier packages

- nab-common/src/main/java/ru/hh/nab/common/properties/FileSettings.java
- nab-kafka/src/main/java/ru/hh/nab/kafka/util/ConfigProvider.java
- nab-kafka/src/test/java/ru/hh/nab/kafka/util/ConfigProviderTest.java
- nab-testbase-old/src/main/resources/service-test.properties
- nab-testbase/src/main/resources/service-test.properties
https://jira.hh.ru/browse/HH-142987
Теперь будем падать при виде неизвестных настроек кафка-продюсера.
> HH-142987 fail on unknown kafka producer settings

- nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/SeekToFirstNotAckedMessageErrorHandler.java
- nab-logging/pom.xml
- pom.xml
https://jira.hh.ru/browse/HH-142689
Перенёс логгирование повыше, чтобы возможные ошибки в обработчике не приводили к отсутствию лога.
> HH-142689 log the error earlier

- pom.xml
https://jira.hh.ru/browse/HH-146692
> HH-146692 add jakarta.ws.rs-api to dependencyManagement

- .hh-release.yaml
- nab-starter/src/main/java/ru/hh/nab/starter/NabLogbackBaseConfigurator.java
https://jira.hh.ru/browse/HH-142674
Вынес GlobalTimeoutCheck в отдельный лог-файл, а то спамит в service.slog.
> HH-142674 move GlobalTimeoutCheck to a separate log file

- nab-common/src/main/java/ru/hh/nab/common/mdc/MDC.java
- nab-common/src/main/java/ru/hh/nab/common/util/ExceptionUtils.java
- nab-common/src/test/java/ru/hh/nab/common/util/ExceptionUtilsTest.java
- nab-starter/src/main/java/ru/hh/nab/starter/exceptions/ExceptionUtils.java
- nab-starter/src/main/java/ru/hh/nab/starter/exceptions/MappableExceptionUtils.java
https://jira.hh.ru/browse/HH-150399
Добавил корректную обработку ошибок в MDC.runWithRequestId
> HH-150399 properly handle exceptions in MDC.runWithRequestId

- nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/DefaultConsumerFactory.java
- nab-kafka/src/main/java/ru/hh/nab/kafka/util/ConfigProvider.java
https://jira.hh.ru/browse/HH-150522
> HH-150522 support concurrency for kafka consumer

- nab-common/pom.xml
- nab-data-source/pom.xml
- nab-example/pom.xml
- nab-hibernate/pom.xml
- nab-jclient/pom.xml
- nab-kafka/pom.xml
- nab-logging/pom.xml
- nab-metrics/pom.xml
- nab-starter/pom.xml
- nab-telemetry-kafka/pom.xml
- nab-telemetry/pom.xml
- nab-testbase/pom.xml
- nab-tests/pom.xml
- nab-websocket/pom.xml
- pom.xml
https://jira.hh.ru/browse/HH-151368
> HH-151368 move to public-pom with spring-boot-dependencies

- .hh-release.yaml
- changelog.yaml
https://jira.hh.ru/browse/HH-153147
> HH-153147 move changelog from wiki

- nab-logging/pom.xml
- nab-starter/src/main/java/ru/hh/nab/starter/NabApplication.java
- nab-tests/src/test/java/ru/hh/nab/starter/NabApplicationTest.java
https://jira.hh.ru/browse/HH-158520
> HH-158520 update sentry version to 6.4.0

- nab-data-source/src/main/java/ru/hh/nab/datasource/DataSourceType.java
- nab-hibernate/src/main/java/ru/hh/nab/hibernate/NabHibernateCommonConfig.java
- nab-hibernate/src/main/java/ru/hh/nab/hibernate/datasource/RoutingDataSource.java
- nab-hibernate/src/main/java/ru/hh/nab/hibernate/transaction/DataSourcesReadyTarget.java
- nab-hibernate/src/main/java/ru/hh/nab/hibernate/transaction/ExecuteOnDataSourceBeanPostProcessor.java
- nab-tests/src/test/java/ru/hh/nab/datasource/ExecuteOnDataSourceAspectTest.java
https://jira.hh.ru/browse/HH-120101
1. Added application BeanPostProcessor to catch misconfiguration
of ExecuteOnDataSource annotation.
2. Removed default fallback to master for RoutingDataSource.
> HH-120101 : Added validation rule for ExecuteOnDataSource

- nab-testbase/src/main/java/ru/hh/nab/testbase/redis/EmbeddedRedisFactory.java
https://jira.hh.ru/browse/HH-165563
> HH-165563 up REDIS version, make REDIS_IMAGE_ENV_VARIABLE public

- nab-starter/src/main/java/ru/hh/nab/starter/exceptions/NabExceptionMapper.java
- nab-starter/src/main/java/ru/hh/nab/starter/exceptions/WebApplicationExceptionMapper.java
https://jira.hh.ru/browse/HH-175639
> HH-175639 add logging of BAD_GATEWAY errors to WebApplicationExceptionMapper

- nab-telemetry-jdbc/pom.xml
- nab-telemetry-jdbc/src/main/java/ru/hh/nab/telemetry/jdbc/internal/NabTelemetryStatement.java
- nab-telemetry-jdbc/src/test/java/ru/hh/nab/telemetry/jdbc/internal/NabTelemetryStatementTest.java
https://jira.hh.ru/browse/HH-177754
> HH-177754 skip SET TIMEOUT jdbc spans

- nab-telemetry-jdbc/src/main/java/ru/hh/nab/telemetry/jdbc/NabTelemetryDataSourceFactory.java
- nab-telemetry-jdbc/src/main/java/ru/hh/nab/telemetry/jdbc/NabTelemetryJdbcProdConfig.java
https://jira.hh.ru/browse/HH-178132
> HH-178132 disable opentelemtry-jdbc span sending by default 

- nab-data-source/pom.xml
- nab-data-source/src/main/java/ru/hh/nab/datasource/DatabaseSwitcher.java
Фикс замечания https://github.com/hhru/nuts-and-bolts/pull/419#discussion_r1293137369
> HH-189050 inject DatabaseSwitcher to DataSourceContextUnsafe in afterPropertiesSet method

- nab-common/pom.xml
- nab-data-source/pom.xml
- nab-example/pom.xml
- nab-hibernate/pom.xml
- nab-jclient/pom.xml
- nab-kafka/pom.xml
- nab-logging/pom.xml
- nab-metrics/pom.xml
- nab-starter/pom.xml
- nab-telemetry-jdbc/pom.xml
- nab-telemetry-kafka/pom.xml
- nab-telemetry/pom.xml
- nab-testbase/pom.xml
- nab-tests/pom.xml
- nab-websocket/pom.xml
- pom.xml
https://jira.hh.ru/browse/HH-192597
> HH-192597 fix snapshot version

- nab-common/src/main/java/ru/hh/nab/common/qualifier/NamedQualifier.java
- nab-jclient/src/main/java/ru/hh/nab/jclient/NabJClientConfig.java
- pom.xml
https://jira.hh.ru/browse/HH-191045
подробнее в описании к https://jira.hh.ru/browse/HH-191037
> HH-191045 support default http client context supplier

- nab-common/src/main/java/ru/hh/nab/common/mdc/MDC.java
- nab-starter/src/main/java/ru/hh/nab/starter/filters/ResourceNameLoggingFilter.java
- nab-telemetry/src/main/java/ru/hh/nab/telemetry/TelemetryFilter.java
- nab-telemetry/src/test/java/ru/hh/nab/telemetry/TelemetryTest.java
https://jira.hh.ru/browse/HH-199932
> HH-199932 additional information about invocation for otlp spans

- nab-starter/pom.xml
- nab-starter/src/main/java/ru/hh/nab/starter/exceptions/AnyExceptionMapper.java
- nab-starter/src/main/java/ru/hh/nab/starter/exceptions/CompletionExceptionMapper.java
- nab-starter/src/main/java/ru/hh/nab/starter/exceptions/ExecutionExceptionMapper.java
- nab-starter/src/main/java/ru/hh/nab/starter/exceptions/IllegalArgumentExceptionMapper.java
- nab-starter/src/main/java/ru/hh/nab/starter/exceptions/IllegalStateExceptionMapper.java
- nab-starter/src/main/java/ru/hh/nab/starter/exceptions/NotFoundExceptionMapper.java
- nab-starter/src/main/java/ru/hh/nab/starter/exceptions/SecurityExceptionMapper.java
- nab-starter/src/main/java/ru/hh/nab/starter/exceptions/WebApplicationExceptionMapper.java
- pom.xml
version changes : PATCH
compatible : true
description :
- added dependency microprofile-openapi-api which provides Microprofile annotations for OpenAPI generator
- added dependency errors-common which provides a general model for API errors
- edited ExceptionMapper descendants - added Microprofile annotations for OpenAPI
> HH-196375 : Microprofile annotations for ExceptionMapper

- nab-data-source/src/main/java/ru/hh/nab/datasource/DelegatingDataSource.java
- nab-logging/src/test/java/ru/hh/nab/logging/HhSyslogAppenderTest.java
- nab-starter/src/main/java/ru/hh/nab/starter/server/jetty/JettyWebAppContext.java
- nab-starter/src/main/java/ru/hh/nab/starter/servlet/NabJerseyConfig.java
- nab-testbase/src/main/java/ru/hh/nab/testbase/listeners/TestExecutorListener.java
- nab-tests/src/test/java/ru/hh/nab/websocket/WebsocketTest.java
https://jira.hh.ru/browse/HH-200499
* ~~Добавил `stringtype=unspecified` в дефолтный postgres jdbc url.~~
* Пофиксил адрес хоста jenkins (странно, конечно, что он торчит в публичном репозитории).
* И пофиксил некоторые предупреждения компилятора.
> HH-200499 some fixes

- nab-starter/src/main/java/ru/hh/nab/starter/NabApplication.java
https://jira.hh.ru/browse/HH-203673
> HH-203673 set sentry release from env

- nab-telemetry/pom.xml
- nab-telemetry/src/test/java/ru/hh/nab/telemetry/TelemetryTest.java
> HH-206877 fix unstable test

- pom.xml
https://jira.hh.ru/browse/HH-207151
> HH-207151: up jclient

- nab-common/src/main/java/ru/hh/nab/common/executor/MonitoredThreadPoolExecutor.java
- nab-metrics/src/main/java/ru/hh/nab/metrics/CompactHistogram.java
- nab-metrics/src/test/java/ru/hh/nab/metrics/HistogramTest.java
version changes : minor
compatible : true
description : 
1. Changed task duration metric's compute strategy for MonitoredThreadPoolExecutor
2. Add new CompactHistogram API for metrics
> HH-204150 : Change metric computation strategy for MonitoredThreadPoolExecutor

- nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/DefaultConsumerFactory.java
- nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/SeekToFirstNotAckedMessageErrorHandler.java
> HH-208578 replace BatchErrorHandler a CommonErrorHandler

- nab-common/src/main/java/ru/hh/nab/common/executor/MonitoredThreadPoolExecutor.java
- nab-data-source/src/main/java/ru/hh/nab/datasource/DataSourceSettings.java
- nab-data-source/src/main/java/ru/hh/nab/datasource/monitoring/NabMetricsTrackerFactory.java
- pom.xml
> HH-190660 remove hardcode of counters/histogram properties

- pom.xml
https://jira.hh.ru/browse/HH-210162
> HH-210162: up public-pom

- pom.xml
> HH-210445 up dependencies

- pom.xml
> HH-211283 up JClient to 3.12.12

- nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/DefaultConsumerFactory.java
- nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/KafkaConsumerFactory.java
> HH-211269 : Add generated clientId for kafka consumers

- changelog.yaml
> HH-211269 : Add forgotten changelog description

- nab-testbase/pom.xml
> HH-211974 : Update kafka-test-utils to 0.0.15

- nab-common/src/main/java/ru/hh/nab/common/constants/RequestAttributes.java
- nab-common/src/main/java/ru/hh/nab/common/mdc/MDC.java
- nab-starter/src/main/java/ru/hh/nab/starter/exceptions/AnyExceptionMapper.java
- nab-starter/src/main/java/ru/hh/nab/starter/exceptions/CompletionExceptionMapper.java
- nab-starter/src/main/java/ru/hh/nab/starter/exceptions/ExecutionExceptionMapper.java
- nab-starter/src/main/java/ru/hh/nab/starter/exceptions/IllegalArgumentExceptionMapper.java
- nab-starter/src/main/java/ru/hh/nab/starter/exceptions/IllegalStateExceptionMapper.java
- nab-starter/src/main/java/ru/hh/nab/starter/exceptions/NabExceptionMapper.java
- nab-starter/src/main/java/ru/hh/nab/starter/exceptions/NotFoundExceptionMapper.java
- nab-starter/src/main/java/ru/hh/nab/starter/exceptions/SecurityExceptionMapper.java
- nab-starter/src/main/java/ru/hh/nab/starter/exceptions/WebApplicationExceptionMapper.java
- nab-starter/src/main/java/ru/hh/nab/starter/filters/ErrorAcceptFilter.java
- nab-starter/src/main/java/ru/hh/nab/starter/filters/ResourceInformationFilter.java
- nab-starter/src/main/java/ru/hh/nab/starter/jersey/DefaultResourceConfig.java
- nab-starter/src/main/java/ru/hh/nab/starter/jersey/NabPriorities.java
- nab-telemetry/src/main/java/ru/hh/nab/telemetry/TelemetryFilter.java
- nab-tests/src/test/java/ru/hh/nab/starter/filters/ResourceInformationFilterTest.java
> HH-213668 improve ResourceInformationLoggingFilter

- nab-common/pom.xml
- nab-data-source/pom.xml
- nab-example/pom.xml
- nab-hibernate/pom.xml
- nab-jclient/pom.xml
- nab-kafka/pom.xml
- nab-logging/pom.xml
- nab-metrics/pom.xml
- nab-starter/pom.xml
- nab-telemetry-jdbc/pom.xml
- nab-telemetry-kafka/pom.xml
- nab-telemetry/pom.xml
- nab-testbase/pom.xml
- nab-tests/pom.xml
- nab-websocket/pom.xml
- pom.xml
> HH-214598 up public-pom

- .hh-release.yaml
- nab-telemetry/src/main/java/ru/hh/nab/telemetry/TelemetryListenerImpl.java
- nab-telemetry/src/test/java/ru/hh/nab/telemetry/TelemetryListenerTest.java
- pom.xml
> HH-214587 add dest host for telemetry

- changelog-jakarta.yaml
> HH-220030 add changelog-jakarta

- nab-common/pom.xml
- nab-data-source/pom.xml
- nab-example/pom.xml
- nab-hibernate/pom.xml
- nab-jclient/pom.xml
- nab-jpa/pom.xml
- nab-kafka/pom.xml
- nab-logging/pom.xml
- nab-metrics/pom.xml
- nab-starter/pom.xml
- nab-telemetry-jdbc/pom.xml
- nab-telemetry-kafka/pom.xml
- nab-telemetry/pom.xml
- nab-testbase/pom.xml
- nab-tests/pom.xml
- nab-websocket/pom.xml
- pom.xml
> HH-221461 up kafka-client-utils and timing-logger

- changelog-jakarta.yaml
- nab-common/pom.xml
- nab-data-source/pom.xml
- nab-data-source/src/main/java/ru/hh/nab/datasource/NabDataSourceCommonConfig.java
- nab-example/pom.xml
- nab-hibernate/pom.xml
- nab-jclient/pom.xml
- nab-jpa/pom.xml
- nab-jpa/src/main/java/ru/hh/nab/jpa/NabJpaCommonConfig.java
- nab-kafka/pom.xml
- nab-logging/pom.xml
- nab-metrics/pom.xml
- nab-starter/pom.xml
- nab-telemetry-jdbc/pom.xml
- nab-telemetry-kafka/pom.xml
- nab-telemetry/pom.xml
- nab-testbase/pom.xml
- nab-tests/pom.xml
- nab-tests/src/test/java/ru/hh/nab/datasource/DataSourceContextTest.java
- nab-tests/src/test/java/ru/hh/nab/datasource/DataSourceTestConfig.java
- nab-websocket/pom.xml
- pom.xml
> HH-222699 fix NabDataSourceCommonConfig

- changelog-jakarta.yaml
- nab-common/pom.xml
- nab-data-source/pom.xml
- nab-example/pom.xml
- nab-hibernate/pom.xml
- nab-jclient/pom.xml
- nab-jpa/pom.xml
- nab-jpa/src/main/java/ru/hh/nab/jpa/NabEntityManagerFactoryBean.java
- nab-jpa/src/main/java/ru/hh/nab/jpa/NabJpaCommonConfig.java
- nab-jpa/src/main/java/ru/hh/nab/jpa/NabPersistenceUnitPostProcessor.java
- nab-kafka/pom.xml
- nab-logging/pom.xml
- nab-metrics/pom.xml
- nab-starter/pom.xml
- nab-telemetry-jdbc/pom.xml
- nab-telemetry-kafka/pom.xml
- nab-telemetry/pom.xml
- nab-testbase/pom.xml
- nab-tests/pom.xml
- nab-websocket/pom.xml
- pom.xml
> HH-222905 remove entities scanning from NabEntityManagerFactoryBean

- nab-kafka/src/main/java/ru/hh/nab/kafka/monitoring/KafkaStatsDReporter.java
1. Changed `client-id` tag name to `client_id` in KafkaStatsDReporter for Okmeter compatability
> HH-226287 : Changing tag key name in KafkaStatsDReporter

- nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/DefaultConsumerFactory.java
- nab-kafka/src/main/java/ru/hh/nab/kafka/monitoring/KafkaStatsDReporter.java
- nab-kafka/src/main/java/ru/hh/nab/kafka/producer/KafkaProducerFactory.java
- nab-kafka/src/main/java/ru/hh/nab/kafka/util/ConfigProvider.java
- nab-tests/src/test/java/ru/hh/nab/kafka/monitoring/KafkaStatsDReporterTest.java
1. Fixed issues with KafkaStatsDReporter metrics beeing send only once - at start
> HH-226616 : Fixed issue with missing metrics for new KafkaStatsDReporter

- nab-web-spring-boot-starter/pom.xml
- nab-web-spring-boot-starter/src/main/java/ru/hh/nab/autoconfigure/AutoConfigurationWhitelist.java
- nab-web-spring-boot-starter/src/main/java/ru/hh/nab/env/AutoConfigurationPropertiesEnvironmentPostProcessor.java
- nab-web-spring-boot-starter/src/main/java/ru/hh/nab/web/NabWebAutoConfiguration.java
- nab-web-spring-boot-starter/src/main/resources/META-INF/spring.factories
- nab-web-spring-boot-starter/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
- nab-web-spring-boot-starter/src/main/resources/META-INF/spring/ru.hh.nab.autoconfigure.AutoConfigurationWhitelist.imports
- nab-web-spring-boot-starter/src/test/java/ru/hh/nab/env/AutoConfigurationPropertiesEnvironmentPostProcessorTest.java
> HH-227882 add auto configurations filtration

- nab-kafka/src/main/java/ru/hh/nab/kafka/monitoring/KafkaStatsDReporter.java
- Fixed issue with missing client id tag
> HH-230125 : Fix issues with missing client id tag

- nab-kafka/src/main/java/ru/hh/nab/kafka/monitoring/KafkaStatsDReporter.java
- nab-tests/src/test/java/ru/hh/nab/kafka/monitoring/KafkaStatsDReporterTest.java
1. Add partition tag for kafka metrics
> HH-230943 : Add partition tag for kafka metrics

- nab-common/pom.xml
- nab-kafka/src/main/java/ru/hh/nab/kafka/monitoring/KafkaStatsDReporter.java
- nab-kafka/src/main/java/ru/hh/nab/kafka/producer/KafkaProducerFactory.java
- nab-kafka/src/main/java/ru/hh/nab/kafka/util/ConfigProvider.java
- nab-kafka/src/test/java/ru/hh/nab/kafka/util/ConfigProviderTest.java
- nab-metrics/src/main/java/ru/hh/nab/metrics/StatsDConstants.java
- nab-metrics/src/main/java/ru/hh/nab/metrics/clients/JvmMetricsSender.java
- nab-metrics/src/main/java/ru/hh/nab/metrics/factory/StatsDClientFactory.java
- nab-starter/src/main/java/ru/hh/nab/starter/NabCommonConfig.java
- nab-starter/src/main/java/ru/hh/nab/starter/NabProdConfig.java
- nab-telemetry-kafka/src/main/java/ru/hh/nab/telemetry/TelemetryAwareProducerFactory.java
- nab-tests/src/test/java/ru/hh/nab/datasource/DataSourceTestConfig.java
- nab-tests/src/test/java/ru/hh/nab/kafka/KafkaTestConfig.java
- nab-tests/src/test/java/ru/hh/nab/kafka/monitoring/KafkaStatsDReporterTest.java
- Simplified construction for Statsd client
- Changed ConfigProvider API contract, added StatsD client as a required field
1. If you're using ConfigProvider - add StatsDSender as an injection dependency
> HH-228751 : Simplified construction for Statsd client

- nab-starter/src/main/java/ru/hh/nab/starter/NabServletContextConfig.java
- nab-starter/src/main/java/ru/hh/nab/starter/filters/SentryFilter.java
> HH-207270 use rid as sentry trace id

- nab-starter/src/main/java/ru/hh/nab/starter/filters/SentryFilter.java
- nab-telemetry/src/main/java/ru/hh/nab/telemetry/IdGeneratorImpl.java
> HH-233707 remove error log in SentryFilter

- nab-hibernate/src/main/java/ru/hh/nab/hibernate/NabHibernateProdConfig.java
> HH-235012 add Session bean declaration to NabHibernateProdConfig

- nab-starter/src/main/java/ru/hh/nab/starter/NabApplication.java
> HH-238516 add startup time logging

- pom.xml
> HH-241309: up jclient

- nab-telemetry/src/main/java/ru/hh/nab/telemetry/TelemetryListenerImpl.java
- nab-telemetry/src/test/java/ru/hh/nab/telemetry/TelemetryListenerTest.java
> HH-241720 remove host resolve for tracing

- nab-starter/pom.xml
https://jira.hh.ru/browse/HH-241839
Исправил зависимость на jackson-jakarta-rs-json-provider.
> HH-241839 fix jackson json-provider dependency

- nab-starter/src/main/java/ru/hh/nab/starter/server/logging/StructuredRequestLogger.java
> HH-243564 fix NPE in StructuredRequestLogger

- nab-starter/src/main/java/ru/hh/nab/starter/server/jetty/HHServerConnector.java
> HH-232356 change log level for 'low on threads'

- nab-starter/src/main/java/ru/hh/nab/starter/NabApplication.java
- nab-starter/src/main/java/ru/hh/nab/starter/server/logging/SentryAppenderInterceptor.java
https://jira.hh.ru/browse/HH-240776
> HH-240776 - divide sentry eof issues by controllers 
